# Path
DEFAULT_DIR_PATH_=''
FUNC_DIR_PATH_=''
GIT_CONFIG_PATH_=''
BREW_CONFIG_PATH_=''
SHELL_CONFIG_PATH_=''
ZSH_CONFIG_PATH_=''
ZSH_HOME_PATH_=''
ZSH_THEME_PATH_=''
BASH_PROFILE_PATH_=''
POWER_LEVEL_9K_PATH_=''
UTILITIES_FUNC_PATH_=''

# Another purpose
IS_PRIVATE=''
CASK_PACKAGES_TO_INSTALL=''
GENERAL_PACKAGES_TO_INSTALL=''